/**
 * The three things the recogniser needs besides the screenshot.
 *
 * All of it is generated by the scripts in tools/ and fetched once. The
 * icon atlas is the only large piece, and it comes as a PNG so the browser
 * decodes it rather than us: drawing it to a canvas gives back exactly the
 * RGBA bytes that the matcher compares against.
 */

export interface IconEntry {
  id: number;
  /** Offset into `pixels`, in RGBA bytes. */
  at: number;
  w: number;
  h: number;
}

export interface Icons {
  entries: IconEntry[];
  pixels: Uint8ClampedArray;
  /** Row stride of `pixels`, in bytes. */
  stride: number;
}

/** A glyph template: one string per row, '#' where the font puts a pixel. */
export interface Glyph {
  c: string;
  rows: string[];
}

export interface Font {
  /** A gap at least this wide is a space rather than letter spacing. */
  space: number;
  /** Widest first, so a shape that is part of a wider one never wins early. */
  glyphs: Glyph[];
}

export interface Anchor {
  x: number;
  y: number;
  w: number;
  h: number;
  /** 1 where the window draws black, 0 where it does not; row major. */
  ink: Uint8Array;
}

export interface WindowLayout {
  id: 'equipment' | 'status' | 'basic-info';
  title: string;
  anchor: Anchor;
  tabs?: {
    probeY: number;
    items: { key: 'primary' | 'secondary' | 'title'; x: number }[];
  };
  slots?: {
    rows: number;
    firstY: number;
    pitch: number;
    iconSize: number;
    columns: { side: 'left' | 'right'; iconX: number; textX: number; textW: number }[];
  };
  stats?: {
    firstY: number; pitch: number; height: number;
    valueX: number; valueW: number; costX: number; costW: number;
  };
  derived?: {
    firstY: number; pitch: number; height: number;
    left: { x: number; w: number; keys: string[] };
    right: { x: number; w: number; keys: string[] };
  };
  body?: [number, number, number, number];
}

export interface Assets {
  icons: Icons;
  font: Font;
  windows: WindowLayout[];
}

let cached: Promise<Assets> | null = null;

/** Loaded once per session and shared; nothing here changes at runtime. */
export function loadAssets(base = './recognition'): Promise<Assets> {
  cached ??= fetchAssets(base);
  return cached;
}

/**
 * Supply the assets directly instead of fetching them.
 *
 * The browser gets the icon atlas decoded by `createImageBitmap` and a
 * canvas; tests have neither, and read the same files off disk instead.
 */
export function provideAssets(assets: Assets): void {
  cached = Promise.resolve(assets);
}

export interface IconManifest {
  cell: number;
  columns: number;
  entries: { id: number; w: number; h: number }[];
}

/** Index the atlas: where each icon starts in the decoded pixel buffer. */
export function packIcons(
  manifest: IconManifest, pixels: Uint8ClampedArray, width: number,
): Icons {
  const stride = width * 4;
  const entries = manifest.entries.map((entry, index) => {
    const x = (index % manifest.columns) * manifest.cell;
    const y = Math.floor(index / manifest.columns) * manifest.cell;
    return { id: entry.id, w: entry.w, h: entry.h, at: y * stride + x * 4 };
  });
  return { entries, pixels, stride };
}

export type RawLayout = { windows: RawWindow[] };

export function decodeLayout(raw: RawLayout): WindowLayout[] {
  return raw.windows.map((w) => ({
    ...w,
    anchor: { ...w.anchor, ink: decodeBase64(w.anchor.ink) },
  }));
}

async function fetchAssets(base: string): Promise<Assets> {
  const [icons, font, layout] = await Promise.all([
    loadIcons(base),
    getJSON<Font>(`${base}/font.json`),
    getJSON<RawLayout>(`${base}/layout.json`),
  ]);

  return { icons, font, windows: decodeLayout(layout) };
}

type RawWindow = Omit<WindowLayout, 'anchor'> & {
  anchor: Omit<Anchor, 'ink'> & { ink: string };
};

async function loadIcons(base: string): Promise<Icons> {
  const [manifest, bitmap] = await Promise.all([
    getJSON<IconManifest>(`${base}/icons.json`),
    fetch(`${base}/icons.png`)
      .then((r) => r.blob())
      .then(createImageBitmap),
  ]);

  const canvas = document.createElement('canvas');
  canvas.width = bitmap.width;
  canvas.height = bitmap.height;
  const ctx = canvas.getContext('2d', { willReadFrequently: true });
  if (!ctx) throw new Error('no 2d canvas context');
  ctx.drawImage(bitmap, 0, 0);
  const { data } = ctx.getImageData(0, 0, bitmap.width, bitmap.height);
  const width = bitmap.width;
  bitmap.close();

  return packIcons(manifest, data, width);
}

async function getJSON<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} -> ${res.status} ${res.statusText}`);
  return (await res.json()) as T;
}

function decodeBase64(text: string): Uint8Array {
  const binary = atob(text);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}
