/**
 * The server's loot bonuses per item: "Zeny Limit on kill" (bonus2 bAddGetZenyNum,N,R) and drop rate
 * (bDropAddRace / bDropAddClass), from the returntomorroc/ item scripts, written to
 * combat/data/server-loot.json for tools/farm.ts (--mode afk scores zeny and relic drops an hour).
 *
 *   node --experimental-strip-types --no-warnings --import ./register.mjs tools/import-loot.ts
 *
 * The server (mob.cpp:2909, pc.cpp:4027, verified 2026-10-04): bAddGetZenyNum adds up -- caps and chances --
 * and a kill pays 1..(sum of caps) at random when the chance roll passes (every item here has chance 100).
 * bGetZenyNum (Cramp Card, the Show Me The Zeny costume) only takes hold over a lower chance, so next to
 * any bAddGetZenyNum it does nothing; it is left out. Drop rate: the killer's bDropAddRace for the
 * monster's race (or RC_All) and bDropAddClass (Class_All), added, then
 * rate = floor(0.5 + base * (100 + bonus) / 100) (mob.cpp:2493).
 *
 * A bonus is evaluated at refine 0..15 (".@r = getrefine()" and its arithmetic), so per-refine ones keep
 * their integer division; one inside an if() on the refine is read as if always on (few are; noted per item).
 * A card's getrefine() is its host item's refine. Combos (item_combo_db) are not read here: the Pirate King
 * set's hidden +10 + refines is in tools/farm.ts.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { REPO } from '../src/data.ts';

const FILES = ['item_db_equip.yml', 'item_db_etc.yml', 'item_db_usable.yml'];
const REFINES = 16;

interface Loot { id: number; name: string; zeny?: number[]; drop?: { race: string; byRefine: number[] }[]; conditional?: true }

/** An item script's expression at a refine: ".@r", "getrefine()", integers, + - * / ( ). */
function evalAt(expr: string, vars: Record<string, string>, r: number): number | null {
  let e = expr.trim();
  for (const [k, v] of Object.entries(vars)) e = e.split(k).join(`(${v})`);
  e = e.replace(/getrefine\(\)/g, String(r));
  if (!/^[\d\s+\-*/()]+$/.test(e)) return null;
  // Integer arithmetic as the script engine does it: division truncates.
  const js = e.replace(/(\([^()]*\)|\d+)\s*\/\s*(\([^()]*\)|\d+)/g, 'Math.trunc($1/$2)');
  try { return Number(Function(`return (${js});`)()); } catch { return null; }
}

const out: Loot[] = [];
for (const file of FILES) {
  const text = readFileSync(resolve(REPO, 'returntomorroc/db/re', file), 'utf8').replace(/\r\n/g, '\n');
  for (const block of text.split(/\n  - Id: /).slice(1)) {
    const id = Number(block.slice(0, block.indexOf('\n')));
    const name = /\n    Name: (.+)/.exec(block)?.[1]?.trim().replace(/^"|"$/g, '') ?? '';
    const script = /\n    Script: \|\n((?: {6}.*\n?)*)/.exec(block)?.[1] ?? '';
    if (!/bAddGetZenyNum|bDropAddRace|bDropAddClass/.test(script)) continue;
    const vars: Record<string, string> = {};
    for (const m of script.matchAll(/(\.@\w+)\s*=\s*([^;]+);/g)) vars[m[1]] = m[2];
    const row: Loot = { id, name };
    if (/\bif\s*\(/.test(script)) row.conditional = true;
    for (const m of script.matchAll(/bonus2 bAddGetZenyNum\s*,\s*([^,]+?)\s*,\s*([^;]+);/g)) {
      const by = Array.from({ length: REFINES }, (_, r) => evalAt(m[1], vars, r) ?? 0);
      row.zeny = row.zeny ? row.zeny.map((v, i) => v + by[i]) : by;
    }
    for (const m of script.matchAll(/bonus2 (bDropAddRace|bDropAddClass)\s*,\s*(\w+)\s*,\s*([^;]+);/g)) {
      const race = m[2] === 'Class_All' ? 'RC_All' : m[2];
      const by = Array.from({ length: REFINES }, (_, r) => evalAt(m[3], vars, r) ?? 0);
      (row.drop ??= []).push({ race, byRefine: by });
    }
    if (row.zeny || row.drop) out.push(row);
  }
}
const file = resolve(REPO, 'combat/data/server-loot.json');
writeFileSync(file, `${JSON.stringify({
  _about: 'Generated by combat/tools/import-loot.ts from returntomorroc/db/re item scripts: per item, zeny limit (bAddGetZenyNum caps) and drop-rate bonuses (bDropAddRace/Class) at refine 0..15. Do not edit by hand.',
  items: out,
})}\n`);
console.log(`${out.length} items -> ${file}`);
for (const n of ['Coat of Riches', 'Treasure Soutane', 'Diamond Ring', 'Pirate Skeleton Card', 'Myst Case Card', 'Fehu Rune of Wealth', 'Zeny Knife', 'Pickpocket Manual X'])
  console.log(n, JSON.stringify(out.find((x) => x.name === n)));
